src/api/rif-marketplace-cache/domainsController.ts
src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
src/components/pages/rns/buy/DomainOffersPage.tsx
src/components/pages/rns/sell/DomainCheckoutPage.tsx
src/components/pages/rns/sell/MyDomainsPage.tsx
src/models/marketItems/DomainItem.ts

fix: converts dates to DateString upon transport

---

src/api/rif-marketplace-cache/cacheController.ts
src/api/rif-marketplace-cache/domainsController.ts
src/api/rif-marketplace-cache/exchangeRateController.ts
src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
src/components/pages/rns/buy/DomainOffersPage.tsx
src/components/pages/rns/sell/DomainCheckoutPage.tsx
src/components/templates/MarketPageTemplate.tsx
src/models/marketItems/DomainItem.ts
src/store/Market/MarketStore.tsx
src/store/Market/marketActions.ts
src/store/Market/marketReducer.ts

Adds currency conversion and resolves #52 .
At this point it is working for RIF and USD only.

feat: adds currency conversion #52

---

src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx

fix: changes wording #65

---

src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
src/components/pages/rns/buy/DomainOffersPage.tsx
src/ui-config.json

Adds the logic for not enough funds and showing own domains.
Closes #49 
Closes #64

Feature/not enough funds #49 #64

---

README.md

Adding installation instructions for the Marketplace UI to the README.md

docs: Adding installation instructions

---

src/api/rif-marketplace-cache/domainsController.ts
src/components/molecules/AddressItem.tsx
src/components/organisms/filters/DomainOffersFilters.tsx
src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
src/components/pages/rns/buy/DomainOffersPage.tsx
src/components/pages/rns/sell/DomainCheckoutPage.tsx
src/components/pages/rns/sell/MyDomainsPage.tsx
src/components/pages/rns/sell/SoldDomainsPage.tsx
src/models/marketItems/DomainItem.ts

feat: Displays and allows movement of domains without reverse name resolution 

---

src/api/rif-marketplace-cache/domainsController.ts
src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
src/components/pages/rns/sell/DomainCheckoutPage.tsx

hotfix: forces contract addresses to lower case to work with rsktestnet

---

src/store/Market/MarketStore.tsx

Currently set to 100 which is rather arbitrary.

fix: sets default max price to 0

---

src/api/rif-marketplace-cache/domainsController.ts

Relates to [this Cache PR](https://github.com/rsksmart/rif-marketplace-cache/pull/87).

feat: removes search term pre&post fix

---

src/components/Routes.tsx
src/components/molecules/FAQSection.tsx
src/components/pages/faq/FAQPage.tsx
src/components/pages/faq/index.ts
src/components/templates/FAQPageTemplate.tsx
src/routes.ts

This PR solves #80 - Created FAQ page
Some components and functionalities included here should go on `rif-ui` as mentioned in #108
The point is that we would need to update `rif-ui` components that are being used in other places (i.e. the filters)

feat: created FAQ page

---

src/api/rif-marketplace-cache/domainsController.ts
src/components/pages/rns/sell/SoldDomainsPage.tsx

Relies on https://github.com/rsksmart/rif-marketplace-cache/pull/96

fix: makes sold domains searchable

---

src/api/rif-marketplace-cache/domainsController.ts
src/components/pages/rns/buy/DomainOffersPage.tsx
src/components/pages/rns/sell/MyDomainsPage.tsx
src/components/pages/rns/sell/SoldDomainsPage.tsx
src/models/marketItems/DomainItem.ts

Depends on this [Cache PR](https://github.com/rsksmart/rif-marketplace-cache/pull/98).
Adds listed price to "Your offers".
Fixes #96

feat: adds price and pseudo resolved name

---

package-lock.json
src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx

feat: waits for funds to be checked before showing no funds message

---

__mocks__/fileMock.ts
package-lock.json
package.json
src/App.test.tsx
src/App.tsx
tsconfig.json

Lets Jest mock files that are not needed for testing such as svg. These files were previously causing the test to crash as it was unable to read them.

fix: fixes tests

---

src/api/rif-marketplace-cache/domainsController.ts

Refs rsksmart/rif-marketplace-cache#116

feat: new TransferItem entity

---

package-lock.json
package.json

Adding reference to the NPM Package now that it is Released.

fix: add reference to RIF UI NPM package

---

package-lock.json
package.json
src/components/atoms/LoginModal.tsx
src/components/hoc/WithAccount.tsx
src/components/templates/marketplace/MarketFilter.tsx

This PR closes #114. Created a HOC to manage actions that need the user to be authenticated to proceed with the desired action.
~### Warning
This PR needs to point to a new version of `rif-ui` that will be released after [this rif-ui PR](https://github.com/rsksmart/rif-ui/pull/58) gets merged into master.
`rif-ui` dependency on `package.json` needs to be updated before merging~

HOC withAccount

---

.eslintrc
src/api/rif-marketplace-cache/domainsController.ts
src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx

Related to [Cache PR#141](https://github.com/rsksmart/rif-marketplace-cache/pull/141).

feat: adjusted domains transport object

---

package.json
src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
src/components/pages/rns/cancel/CancelDomainCheckoutPage.tsx
src/components/pages/rns/sell/DomainCheckoutPage.tsx
src/contracts/Marketplace.ts
src/contracts/Rif.ts
src/contracts/Rns.ts

feat: extract contracts into singletons

---

package-lock.json
package.json
src/contracts/Marketplace.ts
src/ui-config.json

Updates NFTS Marketplace contract to version 0.1.0
Fixes the way to retrieve ABI for Marketplace Contract
Updates New Contract Address for Ganache
Should be merged once the following PR is merged: rsksmart/rif-marketplace-dev#46

feat: add new Marketplace contract

---

src/components/organisms/rns/sell/MyDomains.tsx
src/components/organisms/rns/sell/MyOffers.tsx
src/components/organisms/rns/sell/SoldDomains.tsx
src/components/pages/rns/buy/DomainOffersPage.tsx

Added missed dependencies on the useEffect hooks of Domains pages.
The navigation between buy and sell domains needs to be tested to approve this PR.

fixed dependencies on useEffect hooks

---

src/App.tsx
src/components/atoms/Login.tsx

Parses REACT_APP_REQUIRED_NETWORK_ID environment variable to Number type before comparing with the current networkId

fix: reads proper network

---

package-lock.json
package.json
src/components/atoms/Login.tsx

This PR closes #17 
Gets the available wallets from the provider and list them for the user to choose one to connect

feat: display available wallets

---

src/components/atoms/LoginModal.tsx
src/components/hoc/WithAccount.tsx

This PR closes #202 
- Handles close modal close on HOC
- Reads available providers

Applied latest rif-ui changes to withAccount HOC

---

package.json

* Modify version for Testnet release

chore: change version for release

---

package-lock.json
package.json
src/components/organisms/Footer.tsx
src/components/organisms/filters/DomainOffersFilters.tsx
src/components/pages/rns/sell/DomainCheckoutPage.tsx

This PR closes #217, closes #216 and closes #218  
Handles the price on before submitting a Domain for sell (#218).
Points to a [new version of `rif-ui`](https://github.com/rsksmart/rif-ui/pull/98) that fixes #216 and #217

Handle price and updates rif-ui dependency

---

src/ui-config.json

* Fix URL for Testnet RNS Manager

fix: fix RNS Manager link

---

package-lock.json
package.json
src/components/pages/rns/sell/DomainCheckoutPage.tsx

Closes [#RMKT-240](https://rsklabs.atlassian.net/browse/RMKT-240).
Validates the entered number price before proceeding with the value change

Validates price number before proceeding with value change

---

package-lock.json
package.json
src/ui-config.json

Use new RNS Contract version of the package and address on testnet.

feat: use new rns contract

---

package-lock.json
package.json
src/components/molecules/AddressItem.tsx
src/components/molecules/DomainNameItem.tsx
src/components/organisms/TransactionInProgressPanel.tsx
src/components/organisms/rns/sell/MyDomains.tsx
src/components/organisms/rns/sell/MyOffers.tsx
src/components/organisms/rns/sell/SoldDomains.tsx
src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
src/components/pages/rns/buy/DomainOffersPage.tsx
src/components/pages/rns/cancel/CancelDomainCheckoutPage.tsx
src/components/pages/rns/sell/DomainCheckoutPage.tsx

This PR closes #236 
Added `DomainNameItem` component that shortens the name after specific string length

Handle long domain names

---

package-lock.json
package.json
src/components/molecules/FAQSection.tsx
src/components/organisms/Footer.tsx

closes #238 
Renamed Material-UI ExpansionPanels to Accordions according to their latest version (4.11.0).

Moves MUI ExpansionPanels to Accordions

---

.circleci/config.yml

Removed unsupported node version 13 and added 14 on CircleCI

---

src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
src/components/pages/rns/cancel/CancelDomainCheckoutPage.tsx
src/components/pages/rns/sell/DomainCheckoutPage.tsx

fix: checks domain name before using it

---

package-lock.json
package.json
src/api/models/apiService.ts
src/api/rif-marketplace-cache/config.ts
src/api/rif-marketplace-cache/rns/common.ts
src/api/rif-marketplace-cache/rns/domains.ts
src/api/rif-marketplace-cache/rns/offers.ts
src/api/rif-marketplace-cache/rns/sold.ts
src/store/Market/rns/DomainsStore.tsx
src/store/Market/rns/SoldStore.tsx

Filters certain channels based on the ownerAddress.
The address needs to be send by client in the authentication process.
Currently filtered channels/services are domains and sold domains.
Solves #195 
Solves [RMKT-215](https://rsklabs.atlassian.net/browse/RMKT-215?atlOrigin=eyJpIjoiZjMxMzc3ZDZiZjUzNDI4ZjgxNTk4ZDE4ZDAxN2JkZDMiLCJwIjoiaiJ9)
Relates to [CACHE-PR218](https://github.com/rsksmart/rif-marketplace-cache/pull/218)

hotfix: directed notifications 

---

src/ui-config.json

* Hotfix to restore contract addresses in config files which were overriden by mistake in the last PR.

fix: correct contract address

---

src/api/models/transports.ts
src/api/rif-marketplace-cache/rns/offers.ts

* Include new `id` and `txHash` columns in Domain Sold, Domain Offer and Transfer tables.
* Works together with Cache issue  https://github.com/rsksmart/rif-marketplace-cache/pull/230

feat: support new id column

---

package-lock.json
package.json
src/components/templates/LandingPageTemplate.tsx

This PR removes unneeded text from the landing page.
Also works in conjunction with a [new Pull Request of rif-ui](https://github.com/rsksmart/rif-ui/pull/132) that handles some styles of the same page

chore (styles): removes text from landing

---

package-lock.json
package.json
src/api/models/transports.ts
src/api/rif-marketplace-cache/rns/offers.ts
src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx
src/components/pages/rns/cancel/CancelDomainCheckoutPage.tsx
src/components/pages/rns/sell/DomainCheckoutPage.tsx
src/contracts/Rns.ts
src/ui-config.json

* Restore support for new column `id` for supporting multiple actions in one transaction.
* Update new RNS contract.
* Format messaging and handling additional validation if Token approved/not approved.

feat: rns enhancements

---

src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx

feat: add error description

---

src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx

* Fixes error in string comparison

fix: fix check for approval

---

package-lock.json
package.json

feat: new release

---

src/api/rif-marketplace-cache/rns/offers.ts

Applies better rounding mech for retrieval of rns price limits.

fix: filter min limit

---

package-lock.json
package.json
src/components/organisms/Footer.tsx

* Prepare new version for Release to Testnet.

chore: update version for release

---

src/components/organisms/rns/sell/MyDomains.tsx
src/components/organisms/rns/sell/MyOffers.tsx
src/components/organisms/rns/sell/SoldDomains.tsx
src/components/pages/rns/buy/DomainOffersPage.tsx
src/components/templates/marketplace/Marketplace.tsx

- removes casting to any from item prop assignment

fix: better types and collects marketplace props

---

package-lock.json
package.json
src/components/organisms/Footer.tsx
src/components/pages/FAQPage.tsx
src/components/pages/faq/FAQPage.tsx
src/ui-config.json

* Release for version `1.0.0`
* Updates version, footer and FAQ
* Add contract addresses for Mainnet

chore: final release and version update

---

src/components/pages/storage/sell/StorageSellPage.tsx
src/context/Services/storage/interfaces.ts
src/contracts/Storage.ts
src/ui-config.json

integrate offer creating with multi-currency

feat(offer): multi currency

---

src/api/models/storage/StorageFilter.ts
src/components/organisms/filters/storage/StorageFilters.tsx
src/models/marketItems/StorageFilters.ts

fix: removes name from storage filters and uses provider

---

src/api/models/apiService.ts
src/api/rif-marketplace-cache/blockchain/confirmations.ts
src/api/rif-marketplace-cache/rates/xr.ts
src/api/rif-marketplace-cache/rns/domains.ts
src/api/rif-marketplace-cache/rns/offers.ts
src/api/rif-marketplace-cache/rns/sold.ts
src/components/molecules/RifPaging.tsx
src/components/pages/rns/buy/DomainOffersPage.tsx
src/components/templates/marketplace/Marketplace.tsx
src/store/Market/MarketStore.tsx
src/store/Market/rns/DomainsStore.tsx
src/store/Market/rns/OffersStore.tsx
src/store/Market/rns/SoldStore.tsx
src/store/Market/rns/interfaces.ts
src/store/Market/rns/rnsActions.ts
src/store/Market/rns/rnsReducer.ts

Adds pagination
Contributes towards #384 
Works in tandem with https://github.com/rsksmart/rif-marketplace-cache/pull/320

feat(rns): pagination for mainnet release

---

package-lock.json
package.json
src/ui-config.json

* Bumps version for `storagerManager` and updates address.

feat: new storage address and version

---

src/components/molecules/AddressItem.tsx
src/components/pages/storage/myPurchases/Page.tsx
src/components/pages/storage/myPurchases/utils.tsx

Adds Storage Agreement details modal
Resolving [RMKT-259](https://rsklabs.atlassian.net/browse/RMKT-259)

feat(storage): adds agreement details modal

---

package-lock.json
package.json

Bumps `rif-ui` version to `0.3.1` that has the `src` folder published under the package

Bumps rif-ui version

---

src/components/pages/storage/buy/StorageOffersPage.tsx
src/components/pages/storage/myoffers/StorageMyOffersPage.tsx

Cleans up the offers context on storage offers will unmount and fixes the missing dependencies array that I forgot to add on my previous PR (sorry 😅 )

fix: cleans up context on offers page and my offers will unmount

---

src/components/pages/storage/buy/StorageOffersCheckoutPage.tsx
src/components/pages/storage/myoffers/StorageEditOfferDone.tsx
src/components/pages/storage/myoffers/StorageEditOfferPage.tsx
src/components/pages/storage/myoffers/StorageMyOffersPage.tsx
src/components/pages/storage/sell/StorageSellPage.tsx

* Update the wording and texts on the Storage module.

feat: update storage texts

---

src/api/rif-marketplace-cache/storage/agreements.ts
src/context/storage/mypurchases/renew/Context.tsx

Monthly price calculation didn't include the content size.
This fixes it

fix(storage): agreements monthly price calc w/ size

---

package-lock.json
package.json
src/ui-config.json

* Uses new version of `StorageManager` contract.
* Updates address for `ganache`

feat: new storage contract

---

src/components/organisms/storage/staking/Staking.tsx
src/components/templates/ProgressOverlay.tsx

Closes #415 
*This PR should be squashed*

refactor: makes staking page and progress overlay compatible

---

src/components/organisms/storage/agreements/utils.tsx
src/context/storage/buy/checkout/Context.tsx
src/context/storage/mypurchases/renew/Context.tsx
src/utils/dateUtils.ts

The renewal date calculation for storage agreements was incorrect.
This fixes it.

fix(storage): fixes renewal date calculation

---

src/ui-config.json

* Adds contract addresses for `staging` and `testnet`. 
* Enables `storage` service on Staging.

feat: adds staging and testnet addresses

---

src/components/organisms/storage/sell/PinnerInstructionsModal.tsx

* Fix command for Pinner instructions

chore: fix command for pinner

---

src/api/rif-marketplace-cache/notifications/index.ts
src/context/Services/notifications/Context.tsx

Filters notifications by account.
Resolves #478 
Closes [RMKT-383](https://rsklabs.atlassian.net/jira/software/projects/RMKT/boards/60?assignee=5e84f3015b08780c1c4127b0&selectedIssue=RMKT-383)

fix(notifications): filters by account

---

package-lock.json
package.json
src/ui-config.json

* Uses new version of StorageContract
*Updates addresses for Ganache and Staging.

chore: new contract version and config

---

src/api/rif-marketplace-cache/storage/agreements.ts
src/components/molecules/SelectRowButton.tsx
src/components/organisms/storage/agreements/utils.tsx
src/components/organisms/storage/myoffers/ActiveContracts.tsx
src/components/pages/storage/myPurchases/Page.tsx
src/models/marketItems/StorageItem.ts

Closes #470 
Sometimes we are getting negative periods from the cache, https://github.com/rsksmart/rif-marketplace-cache/pull/384 would fix that

fix(storage): calculates withdrawable funds and disables the action when no funds

---

src/components/pages/storage/buy/StorageOffersPage.tsx

Closes https://github.com/rsksmart/rif-marketplace-ui/issues/464
Depends on https://github.com/rsksmart/rif-marketplace-cache/pull/389

refactor: adapts table header to avg price per month

---

src/contracts/storage/contract.ts

The dataReference argument to SC was not properly encoded before sending.
This fixes #465

fix(storage): fixes dataReference encoding

---

src/components/pages/storage/buy/StorageOffersPage.tsx

Disables the select button for offers created by the current account holder.
Resolves https://rsklabs.atlassian.net/browse/RMKT-395

feat(storage): disables select for own offer

---

src/api/rif-storage-upload-service/upload/index.ts
src/context/Services/storage/upload/Context.tsx

* Fixes the upload service providing the additional parameter. The `storageManager` contract address.

fix: add contractAddress for upload service

---

src/components/organisms/TransactionInProgressPanel.tsx
src/components/pages/storage/myoffers/StorageEditOfferPage.tsx
src/components/pages/storage/sell/StorageSellPage.tsx
src/components/templates/OverlaidPageTemplate.tsx
src/components/templates/ProgressOverlay.tsx

Closes #504 
Overlays the whole screen while executing transactions

feat: adds overlaid page template component

---

src/App.tsx
src/components/Market.tsx
src/components/organisms/AlertPanel.tsx
src/components/pages/storage/buy/StorageOffersPage.tsx
src/constants/strings.ts
src/context/App/AppContext.tsx
src/context/App/appActions.ts

- Moves most of the logic from `AppComponent` to `MarketComponent` (where we can read from `AppContext`).
- Extracts AlertInfo to new component and moves messages logic to AppContext
- Adds disclaimer message - Closes #505

App restructure + Storage disclaimer

---

src/api/rif-marketplace-cache/storage/available-size.ts
src/api/rif-marketplace-cache/storage/interfaces.ts
src/context/App/AppContext.tsx
src/context/Services/storage/offers/OffersContext.tsx

Closes #460 
Depends on https://github.com/rsksmart/rif-marketplace-cache/pull/414

feat(storage): filters and fetches limits by available size

---

src/components/organisms/storage/sell/EditOfferStepper.tsx
src/components/organisms/storage/sell/GeneralFeatures.tsx
src/components/pages/storage/myoffers/StorageEditOfferPage.tsx
src/components/pages/storage/sell/StorageSellPage.tsx
src/context/Market/storage/OfferEditContext.tsx
src/context/Market/storage/__tests__/offerEditActions.test.tsx
src/context/Market/storage/interfaces.ts
src/context/Market/storage/offerEditActions.ts
src/context/Market/storage/offerEditReducer.ts
src/contracts/storage/interfaces.ts
src/contracts/storage/utils.ts

feat(storage): uses totalCapacity for offer edition/creation

---

src/contracts/storage/utils.ts

Fixes [RMKT-438](https://rsklabs.atlassian.net/jira/software/projects/RMKT/boards/60?selectedIssue=RMKT-438) by rounding down the total capacity on offer creation

fix(storage): rounds down listed size on offer creation

---

src/components/pages/storage/buy/StorageOffersPage.tsx

* Asked by QA to clarify that the price is an Average and will not match the End price.

feat: clarify average in column header

---

src/api/rif-marketplace-cache/storage/agreements.ts
src/components/organisms/storage/agreements/utils.tsx
src/components/pages/storage/myPurchases/Page.tsx
src/models/marketItems/StorageItem.ts

- Adds advice for consumer that "withdrawing all funds would terminate the agreement"
- Disables renew action if agreement has expired or is not active
- When agreements have expired, shows "expired" in renewal date, before was today's date by default
In the StorageManager SC - the agreements are not allowed to renew if the current period is the last one. So https://github.com/rsksmart/rif-marketplace-ui/issues/534 and https://github.com/rsksmart/rif-marketplace-ui/issues/535 are on hold for now

feat(storage): adds advice - withdrawing funds terminates agreement

---

package-lock.json
package.json

Closes [RMKT-431](https://rsklabs.atlassian.net/browse/RMKT-431).

chore(deps): bumps rif-ui to v0.4.3

---

src/context/storage/buy/checkout/actions.ts

fix(storage-buy): resets periods and selected plan on currency change

---

src/api/rif-marketplace-cache/rns/common.ts
src/blockchain/config.ts

fix: removes duplicated config file

---

src/components/organisms/storage/staking/Staking.tsx
src/context/storage/buy/checkout/Context.tsx
src/contracts/storage/Staking.ts
src/contracts/storage/Storage.ts
src/contracts/utils/accountBalance.ts
src/models/CustomError.ts

Migrated from #569 
Closes #530 
Closes #417 
Adds `CustomError` class to handle custom errors with user friendly messages

feat: checks available funds before sending tx

---

src/ui-config.json

* Adds addresses for Testnet
* Enables services and tokens for Storage.

chore: config file for Testnet

---

package-lock.json
package.json

* Bump Storage contract version.

chore: new contract version

---

package-lock.json
package.json
src/context/storage/mypurchases/renew/Context.tsx

- Includes token on `txOptions` when renewing agreements - Closes #585 
- Updates `rif-ui` dependency to a new version where the account is given in lowercase by the `Web3Provider`
~Depends on https://github.com/rsksmart/rif-ui/pull/206 that would release new npm version. 
Do not merge until that dependency is updated properly~

fix(storage-agreements): includes token on txOptions when renewing

---

src/components/organisms/storage/staking/DepositModal.tsx
src/components/organisms/storage/staking/Staking.tsx

feat(storage): prevents attempt to stake more than current balance

---

src/components/pages/storage/myoffers/StorageEditOfferPage.tsx
src/components/pages/storage/myoffers/utils.ts
src/context/Market/storage/offerEditReducer.ts
src/contracts/storage/Storage.ts
src/contracts/storage/utils.ts

Closes https://github.com/rsksmart/rif-marketplace-ui/issues/377

feat(storage): optimize edit offer call

---

src/components/pages/storage/buy/StorageOffersCheckoutPage.tsx

* Fixes message when buying storage (Agreement)

chore: storage message

---

src/components/atoms/ItemWUnit.tsx

also refactors component to use classes as in the rest of the app
Related to [RMKT-463](https://rsklabs.atlassian.net/jira/software/projects/RMKT/boards/60?selectedIssue=RMKT-463)

fix(design): avoids new line on ItemWUnit

---

src/components/organisms/storage/agreements/utils.tsx
src/components/organisms/storage/myoffers/ActiveContracts.tsx
src/contracts/storage/utils.ts

- Fixes payoutFunds method by ensuring proper length for encoded hashes
- Adds confirmations functionality to payoutFunds action
Closes #610

feat(storage-agreements): handles payout confirmations

---

src/api/models/transports.ts
src/api/rif-marketplace-cache/rns/__tests__/domains.test.ts
src/api/rif-marketplace-cache/rns/__tests__/offers.test.ts
src/api/rif-marketplace-cache/rns/__tests__/sold.test.ts
src/api/rif-marketplace-cache/rns/domains.ts
src/api/rif-marketplace-cache/rns/offers.ts

This reverts commit 380183155be3ce8c94bd96f794c793f130ecf3d9.

hotfix(rns): reverts adapts expirationDate

---

src/components/organisms/storage/sell/BillingPlan.tsx
src/components/organisms/storage/sell/BillingPlanWithEdit.tsx
src/components/organisms/storage/sell/BillingPlansList.tsx
src/components/organisms/storage/sell/EditOfferStepper.tsx
src/components/organisms/storage/sell/EditableBillingPlan.tsx
src/components/organisms/storage/sell/GeneralFeatures.tsx

refactor(storage): avoids editOfferContext use in children comp

---

src/components/organisms/Header.tsx
src/components/organisms/NotificationsPopover.tsx
src/components/organisms/transactions/TransactionItem.tsx
src/components/organisms/transactions/TransactionsList.tsx
src/components/organisms/transactions/TransactionsPopover.tsx
src/components/templates/PopoverCardTemplate.tsx

- adds txs icon with badge in header
- adds txs panel
- extracts logic and styles from notifications popover to be reused

feat(confirmations): adds transactions panel popover

---

src/ui-config.json

* Updates ganache contract addresses

chore: ganache contract addresses

---

src/components/organisms/storage/buy/PinningCard.tsx

fix(storage-upload): cleans data when switching tabs

---

src/components/organisms/NotificationsPopover.tsx

feat(notifications): adds no notifications message

---

src/api/models/RnsFilter.ts
src/components/organisms/filters/DomainFilters.tsx
src/components/organisms/filters/RadioFilter.tsx
src/components/organisms/rns/sell/MyOffers.tsx
src/components/pages/rns/cancel/CancelDomainCheckoutPage.tsx
src/components/pages/rns/sell/SellDomainsListPage.tsx
src/context/Services/rns/DomainsContext.tsx

- Fixes domain placed cancellation - Closes #682 
- Initialises common rns reducer the proper way (`createReducer`)
- Refactors `CancelDomainCheckoutPage.tsx` component
There are more refactors coming that may impact the same components touched here but let's keep the PRs small :)

refactor(rns): uses proper context for DomainsContext

---

src/components/organisms/rns/sell/MyOffers.tsx

fix(rns-myoffers): fixes listed price format (#665)

---

src/components/atoms/GridItem.tsx
src/components/atoms/GridRow.tsx
src/components/molecules/TitledRoundedCard.tsx
src/components/organisms/triggers/ProviderRegistrar.tsx
src/components/pages/triggers/TriggersRoutes.tsx
src/components/pages/triggers/sell/TriggersSellPage.tsx
src/routes.ts
src/ui-config.json

feat(triggers-sell): adds route + tabs section with sell option

---

package-lock.json
package.json
src/components/organisms/triggers/ProviderRegistrar.tsx
src/components/pages/triggers/sell/TriggersSellPage.tsx

- Adds `react-hook-form` dependency
- Validates data and handles all input data with the new library - reduces logic on page

feat(triggers-sell): handles form data with react-hook-form

---

src/hooks/useErrorReporter.tsx

Closes https://github.com/rsksmart/rif-marketplace-ui/issues/397
Adds ability to report errors easier with:
```
const errorReporter = useErrorReporter()
errorReporter(new UIError({
error: new Error(),
id: 'some-id',
text: 'some text',
}))

feat: adds useErrorReporter custom hook

---

package-lock.json
package.json
src/ui-config.json

* Adds new addresses for contracts in `staging` and `testnet`.
* Bumps version of Storage contract

chore: staging and testnet new contracts

---

.circleci/config.yml
.github/workflows/staging.yml

Staging workflow for CD of marketplace UI

feat: add staging workflow for CD

---

src/components/organisms/storage/mypurchases/PurchasesTable.tsx

... on my purchases page.
This should fix the bug reported in the ticket [RMKT-597](https://rsklabs.atlassian.net/browse/RMKT-597).
Not verified locally as this bug could not be locally reproduced.

fix(storage): adds check for crypto existence

---

.github/workflows/staging.yml

The CD workflow must be added to the proper branch in order to execute correctly.

feat(devops): adding cd fix for staging branch
