rsksmart/rif-marketplace-ui

src/api/rif-marketplace-cache/domainsController.ts, src/components/organisms/filters/DomainOffersFilters.tsx, src/components/pages/rns/buy/DomainOffersPage.tsx, src/models/Market.ts
Closes #50 
Adds a request to the cache to get the min and max price. Calling it from componentWillMount of the DomainOfferFilters, it sets edge values of the RangeFilter component.
As mentioned in the issue this closes, a [rif-ui issue](https://github.com/rsksmart/rif-ui/issues/10) prevents us from changing the inputs associated with the bounds of the range slider programmatically.
The result is that, though the slider itself updates its values, as well as does the marketplace (showing items according to min max boundaries), the <input> parts of the slider are not representing this change.
As soon as this is fixed in the rif-ui, the behaviour should be as expected.
=> feat: adds price bounds fetch, changing filter #50

package-lock.json, package.json, src/components/Routes.tsx, src/components/atoms/Login.tsx, src/components/atoms/LoginModal.tsx, src/components/organisms/Footer.tsx, src/components/organisms/Header.tsx, src/components/organisms/ServiceCategories.tsx, src/components/organisms/filters/DomainFilters.tsx, src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx, src/components/pages/rns/sell/MyDomainsPage.tsx, src/components/pages/storage/StoragePage.tsx, src/components/pages/storage/index.ts, src/components/templates/marketplace/MarketFilter.tsx, src/components/templates/marketplace/Marketplace.tsx
This PR solves #54, #61 and #83 .
- When clicking on sell domains and not logged in, triggers the modal to log in.
- Consumes the new components on `rif-ui` to handle the Account Modal from another React element.
- Updated footer props to match the new `rif-ui` properties
- Removes elements we do not want to show yet in the Header
- Adds min-height to the Filters on desktop
- Created empty Storage Page
- The solution to trigger the modal when switching to the sell domains tab needs to be improved
=> hotfixes - styles and pop up login modal before navigating to sell domains

package-lock.json
Just an updated package-lock file.
=> fix: adds latest rif-ui in the lock

package-lock.json, package.json, src/components/Routes.tsx, src/components/organisms/filters/DomainOffersFilters.tsx, src/components/pages/LandingPage.tsx, src/components/pages/faq/FAQPage.tsx, src/components/pages/index.ts, src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx, src/components/pages/rns/buy/DomainOffersPage.tsx, src/components/pages/rns/buy/index.ts, src/components/pages/rns/index.ts, src/components/pages/rns/sell/DomainCheckoutPage.tsx, src/components/pages/rns/sell/MyDomainsPage.tsx, src/components/pages/rns/sell/SoldDomainsPage.tsx, src/components/pages/rns/sell/index.ts
This PR closes #117 
- Updated `@truffle/contract` dependency to version `4.2.0` that doesn't use regex, not supported by Firefox browser right now.
- Refactored some imports and exports
- Fixed high vulnerability (`http-proxy`)
=> Firefox compatibility

package-lock.json, src/components/Routes.tsx, src/components/pages/rns/cancel/CancelDomainCheckoutPage.tsx, src/components/pages/rns/cancel/DomainCanceled.tsx, src/components/pages/rns/cancel/index.ts, src/components/pages/rns/index.ts, src/components/pages/rns/sell/MyDomainsPage.tsx, src/routes.ts
Main goal: Adds the Canceling a Domain functionality.
Changes:  
- Added IconButton X for Canceling a Listed Domain.
- Adapted routes and flow to be able to Cancel Domain (requires two transactions - The "unapproval" of the Token and the actual "unplace" Transaction)
- Two New pages:
- rns/cancel/DomainCanceled.tsx
- rns/cancel/CancelDomainCheckoutPage.tsx
=> feat: Canceling Domain functionality

src/api/rif-marketplace-cache/domainsController.ts
Linked to [Cache#118](https://github.com/rsksmart/rif-marketplace-cache/pull/118).
Adapts sold domain mapping to the new structure.
=> feat: fixes sold domains transport mapper

package-lock.json, package.json, src/components/Routes.tsx, src/components/pages/FAQPage.tsx, src/components/pages/faq/FAQPage.tsx, src/components/pages/index.ts
Closes #108 
Moved FAQ stuff to `rif-ui`.
This PR depends on [this PR from rif-ui](https://github.com/rsksmart/rif-ui/pull/45).
I would suggest to not merge this PR until the other one is merged so we can point to rif-ui master branch.
=> refactor: moved faq stuff to rif-ui

src/components/pages/storage/StoragePage.tsx
Fixed spaces caused by the linter fixes on Storage page
=> fix: fixed text spacing on storage page

src/components/pages/rns/buy/DomainPurchased.tsx
Disabling RNS Admin Redirect button until we implement this. The URL will depend on the environment, so would probably need to be included in the UI Config file for each network.
=> fix: Disable RNS Admin redirect button

package-lock.json, package.json, src/components/hoc/WithAccount.tsx
This PR closes #169.
~### Warning
Before merging, [this rif-ui PR](https://github.com/rsksmart/rif-ui/pull/63) needs to be merged and included in a new `npm` version. We could then update the `package.json` dependency~
=> fix: close modal on HOC WithAccount once the provider is set

package-lock.json, package.json, src/api/models/RnsFilter.ts, src/api/rif-marketplace-cache/cacheController.ts, src/api/rif-marketplace-cache/domainsController.ts, src/components/molecules/InfoBar.tsx, src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx, src/components/pages/rns/buy/DomainOffersPage.tsx, src/components/pages/rns/sell/MyDomainsPage.tsx, src/components/pages/rns/sell/SoldDomainsPage.tsx, src/components/templates/MarketPageTemplate.tsx, src/models/Market.ts, src/models/marketItems/DomainItem.ts, src/store/Market/MarketStore.tsx, src/store/Market/marketActions.ts, src/store/Market/marketReducer.ts
This PR adds a package @material-ui/lab to allow us to use their Alert and later Pagination components.
This means that you must `npm i` after checking out this PR.
Closes #51 
To test this you will need [Cache PR#130](https://github.com/rsksmart/rif-marketplace-cache/pull/130)
=> feat: adds support for events coming from cache

src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx, src/components/pages/rns/cancel/CancelDomainCheckoutPage.tsx, src/components/pages/rns/sell/DomainCheckoutPage.tsx
* Calculate for each major transaction the `gas` and `gasPrice` values to send in the TX. This enables transactions to be executed and picked up by miners avoiding long waits when sending Tx to the blockchain. Critical for Testnet and Mainnet.
Note: In a future change we can refactor to a utils class instead of doing the logic in each phase.
=> feat: calculate gas limit and gas price for txs

src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx, src/components/pages/rns/buy/DomainPurchased.tsx, src/components/templates/CheckoutPageTemplate.tsx, src/components/templates/TxCompletePageTemplate.tsx, src/ui-config.json
Closes #139 
* Adds link to RNS Manager after you Buy a domain.
* RNS Manager URL has to be defined in the `ui-config.json` file.
* Checks that the URL is defined.
* Postpones Cleanup of `currentOrder` to the Transaction confirmation page.
Note: To test this PR you need to:
1) Run the RNS Manager locally with the LATEST `develop` branch.
2) If you get an error when doing `npm start` in the RNS manager run: `npm i webpack@4.28.3` in the Manager project this should fix the issue. Then try again.
3) Setup the correct RNS manager URL in the `ui-config.json` file of the MArketplace UI project. (samples provided in the default file).
4) **BUY** a domain and then click on the `Admin my domain` button of the confirmation page. You should get a new tab opened directly on the manager page (if you …
=> feat/ Admin your domain option after purchase

package-lock.json, package.json, src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx, src/components/pages/rns/cancel/CancelDomainCheckoutPage.tsx, src/components/pages/rns/sell/DomainCheckoutPage.tsx, src/contracts/Marketplace.ts, src/contracts/Rif.ts, src/contracts/Rns.ts, src/contracts/config.ts, src/contracts/utils.ts
* Includes polling for `TransactionReceipt` in all transactions which is required for compatibility with Nifty wallet.
* Creates Singletons for each Contract (`Marketplace`, `Rif`, `Rns`) which implement proxy functions to avoid including transaction receipt logic on the pages.
* Saves the `web3` instance as attribute of the Contracts to avoid passing it every time.
* Creates a `utils.ts` file in the `/contracts` folder to avoid duplication of code.
* Creates a `config.ts` file to expose the Contract addresses.
Note: `Promise.race` did not help for polling the way we had to do, which is checking repeated times in certain intervals be which was our main requirement, so it was not used. It is helpful for setting up a Timeout so can be considered in other requirements.
Closes #215
=> feat: polling for transaction receipts

package-lock.json, package.json, src/contracts/Marketplace.ts, src/ui-config.json
* Bump NFTS package version to `v0.1.2`
* Use New version of `RNS` contract (which requires to rename the singleton)
* Updates addresses in `ganache` and `rsktestnet` config files.
Works together with Cache PR: https://github.com/rsksmart/rif-marketplace-cache/pull/222 
To deploy Contract locally this PR: https://github.com/rsksmart/rif-marketplace-dev/pull/66
=> feat: use new version of RNS contract

src/api/rif-marketplace-cache/rns/common.ts, src/components/Routes.tsx, src/components/organisms/Header.tsx, src/components/pages/rns/RnsLandingPage.tsx, src/components/pages/rns/RnsRoutes.tsx, src/components/pages/rns/buy/DomainOffersCheckoutPage.tsx, src/components/pages/rns/buy/DomainPurchased.tsx, src/components/pages/rns/sell/DomainCheckoutPage.tsx, src/components/pages/storage/StorageLandingPage.tsx, src/components/pages/storage/StorageRoutes.tsx, src/config.ts, src/contracts/config.ts, src/ui-config.json
This PR closes #269 
Also grouped the addresses in the `ui-config` under a `contractAddresses` attribute and unified the way we were reading them as we had them exported in `src/contracts/config.ts`
=> Controls enabled services from the ui-config file

src/components/organisms/storage/sell/PinnerInstructionsModal.tsx
* Fixes typo in pinner command from `pinner` to `pinning`
=> fix: typo in pinner command

package-lock.json, package.json
Uses `rif-ui@v0.3.2` that has the spinner fixed
=> chore: updates rif-ui version

package-lock.json, package.json
Closes #457. The Slider of the new version of `rif-ui` will trigger changes only on committed.
=> chore: updates rif-ui dependency

src/api/models/storage/StorageFilter.ts, src/api/rif-marketplace-cache/storage/__tests__/offers.test.ts, src/api/rif-marketplace-cache/storage/offers.ts, src/components/organisms/storage/myoffers/ExpandableOffer.tsx, src/components/pages/storage/myoffers/StorageMyOffersPage.tsx, src/components/pages/storage/sell/StorageSellPage.tsx, src/models/marketItems/StorageFilters.ts, src/models/marketItems/StorageItem.ts
- makes all filters optional so we can just filter by provider no matter size or price
- when creating offers, cleans up billing plans if the provider had a previous offer (inactive or not) - Closes #477 
- allows providers to see their inactive offers - Closes #473
=> feat(storage): cleans up previous plans when creating offers & allows providers to see their inactive offers

src/contracts/utils.ts, src/contracts/wrappers/contract-base.ts
* Implements direct polling for receipt when sending all transactions required for Nifty.
Closes #532
=> fix: adds polling for receipt

src/components/pages/storage/sell/StorageSellPage.tsx
It was failing when the user doesn't have any offer created yet, as `currentOwnOffers[0]` was `undefined` and so couldn't destructure `subscriptionOptions`
=> fix(storage): fixes offer creation

src/components/organisms/storage/agreements/utils.tsx
When combining RIF token and RBTC we had some issues displaying the amounts with `toPrecision(X)` so just showing the full amount until we design proper solution
**Before**
**Now**
=> fix: removes precision from agreements available funds

src/api/models/storage/StorageFilter.ts, src/components/organisms/storage/sell/OfferCreation.tsx, src/components/pages/storage/myoffers/StorageMyOffersPage.tsx, src/models/marketItems/StorageFilters.ts
Relates to cache https://github.com/rsksmart/rif-marketplace-cache/pull/432
Problem: word 'non-active' makes an awkward object key.
=> refactor(storage): changes non-active to withInactive

src/context/storage/buy/checkout/Context.tsx
I wrongly dispatched the `inProgress` status to `false` on the `finally` statement. It's reset when setting the status to `done`. By setting it again on the finally it resets the `isDone` prop and so the user is not able to see the thumbs up.
=> fix(storage-buy): avoids reseting done status on success

src/components/pages/storage/myPurchases/Page.tsx
=> fix(storage-purchases): enables scroll view on purchases table

src/components/Market.tsx, src/components/molecules/InfoBar.tsx, src/components/pages/storage/myPurchases/Page.tsx, src/context/Confirmations/Context.tsx, src/context/Confirmations/actions.ts, src/context/Confirmations/index.ts, src/context/Confirmations/interfaces.ts, src/context/Confirmations/utils.ts, src/context/Services/storage/agreements/Context.tsx, src/context/storage/buy/checkout/Context.tsx, src/context/storeUtils/interfaces.ts
`BlockchainContext` and `ConfirmationsContext` should be the same, but for the matter of transition I've created `ConfirmationsContext` to handle confirmations in a new way without interfering with `BlockchainContext` that's being used in many other services. 
Will close #586 
Will add https://github.com/rsksmart/rif-marketplace-ui/issues/607
=> feat(confirmations): adds confirmations context

package-lock.json, package.json, src/components/organisms/storage/agreements/utils.tsx, src/components/organisms/storage/myoffers/ActiveContracts.tsx, src/components/organisms/storage/mypurchases/PurchasesTable.tsx, src/components/pages/storage/myPurchases/Page.tsx, src/context/Confirmations/interfaces.ts, src/context/storage/mypurchases/withdraw/Context.tsx
- Extracts purchases table logic into new component (Page component was getting too big)
- While awaiting for confirmations after a withdraw action, shows spinner on actions column - Closes #609
- Fixes 'withdrawed' message
- Shows spinner while loading agreements
- Bumps `rif-ui` dependency to v0.5.3
- Adds message when no purchases yet
=> feat(storage-purchases): handles confirmations for withdraw

src/components/organisms/storage/agreements/utils.tsx, src/components/organisms/storage/mypurchases/PurchasesTable.tsx, src/components/pages/storage/myPurchases/Page.tsx, src/context/Confirmations/interfaces.ts, src/context/Confirmations/utils.ts, src/context/storage/mypurchases/renew/Context.tsx, src/context/storage/mypurchases/withdraw/Context.tsx
- Refactor confirmations to be able to get by multiple types
- Joins Withdraw, renew and payout action data types into `AgreementUpdateData`, they all only need `agreementId` for now
- Adds confirmations support for renewing agreements
=> feat(storage-agreements): handles renew confirmations

src/components/organisms/storage/mypurchases/PurchasesTable.tsx, src/components/pages/storage/myPurchases/Page.tsx, src/hooks/useConfirmations.tsx
- Adds React custom hook `useConfirmations` to read easily the pending confirmations for a specific action
- Uses this new custom hook in the site (only in agreements as the other ones are not merged yet)
=> feat: adds useConfirmations custom hook to read specific confs easily

src/api/rif-storage-upload-service/upload/index.ts, src/api/rif-storage-upload-service/upload/interfaces.ts, src/components/molecules/storage/buy/PinUploaderTab.tsx, src/components/organisms/storage/buy/PinningCard.tsx, src/context/Services/storage/upload/Context.tsx, src/context/Services/storage/upload/actions.ts, src/context/Services/storage/upload/interfaces.ts
- Gets file size limit from upload-service
- Shows max size text
- Disables upload button until there is content to be uploaded
- Adds spinner on uploader and disables button until files are loaded
By default it's set to 1GB in UI. This allows us to always handle a value without having to "pause" the flow until we have the max size defined
=> feat(storage-upload): adds spinner & disables btn on loading file

src/components/organisms/Header.tsx
=> feat(header): hides custom actions if not logged in

src/components/organisms/notifier/Staking.tsx, src/components/organisms/storage/staking/Staking.tsx, src/context/Confirmations/interfaces.ts, src/contracts/config.ts, src/contracts/interfaces.ts, src/contracts/notifier/Staking.ts, src/contracts/storage/Staking.ts
- Adds Notifier Staking SC wrapper
- Handles stake/unstake in ui
- `canWithdraw` and `stakedBalances` should be read from cache when service is ready
https://user-images.githubusercontent.com/8449567/108768704-be84f380-7536-11eb-8d9a-91fa2c8b9262.mov
_`totalStakedUSD` needs to be hardcoded with a positive number in order to enable this functionality_
https://user-images.githubusercontent.com/8449567/108769244-7fa36d80-7537-11eb-80d0-f800ddc70244.mov
~Rebased on #717~
=> feat: adds notifier staking interaction with SC
